name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Cada día a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate graph
        uses: lowlighter/metrics@latest
        with:
          filename: output/pacman-contribution-graph.svg
          token: ${{ secrets.PACMAN_TOKEN }}
          base: ""
          plugin_contributions: yes
          plugin_contributions_sections: repositories
          plugin_contributions_colors: true
          plugin_contributions_chart: true
          plugin_contributions_lines: 12
          config_output: svg
          config_timezone: Europe/Madrid
          config_twemoji: yes
          plugin_contributions_pacman: yes
